### ISSUE TITLE
your sites problem

### ISSUE THREAD

**Issue by omer-os** [bryankhaw95/port-current#1]
hey, i was just looking for portfolio sites in github and saw your site.
tips to improve this site:
        * make the code simple by deleting unnecessary comments and codes
        * using tailwind css is easy but making its code manageable is hard. your html file is over 300 lines of dummy code all because of messy tailwind css code. dont use tailwind or learn how to make it manageable and simple
        * make your site responsive for all devises

**Comment by bryankhaw95** [comment]
hi Omer, thank you for your comment. I am still researching and learning on working with tailwind css as it is still incomplete.
